name: Compile Examples

on:
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "library.properties"
      - "examples/**"
      - "src/**"
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "library.properties"
      - "examples/**"
      - "src/**"
  # Scheduled trigger checks for breakage caused by changes to external resources (libraries, platforms)
  schedule:
    # run every Saturday at 3 AM UTC
    - cron: "0 3 * * 6"
  # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest

    env:
      UNIVERSAL_LIBRARIES: |
        # install the Arduino_SpiNINA library from the local path
        - source-path: ./
        - name: WiFiNINA
        - name: ArduinoBLE
        - name: VidorPeripherals
      UNIVERSAL_SKETCH_PATHS: |
        - ~/Arduino/libraries/WiFiNINA/examples/AP_SimpleWebServer
        - ~/Arduino/libraries/WiFiNINA/examples/ConnectNoEncryption
        - ~/Arduino/libraries/WiFiNINA/examples/ConnectWithWEP
        - ~/Arduino/libraries/WiFiNINA/examples/ConnectWithWPA
        - ~/Arduino/libraries/WiFiNINA/examples/ConnectWithWPA2Enterprise
        - ~/Arduino/libraries/WiFiNINA/examples/ScanNetworks
        - ~/Arduino/libraries/WiFiNINA/examples/ScanNetworksAdvanced
        - ~/Arduino/libraries/WiFiNINA/examples/SimpleWebServerWiFi
        - ~/Arduino/libraries/WiFiNINA/examples/WiFiAdvancedChatServer
        - ~/Arduino/libraries/WiFiNINA/examples/WiFiChatServer
        - ~/Arduino/libraries/WiFiNINA/examples/WiFiPing
        - ~/Arduino/libraries/WiFiNINA/examples/WiFiSSLClient
        - ~/Arduino/libraries/WiFiNINA/examples/WiFiStorage
        - ~/Arduino/libraries/WiFiNINA/examples/WiFiUdpNtpClient
        - ~/Arduino/libraries/WiFiNINA/examples/WiFiUdpSendReceiveString
        - ~/Arduino/libraries/WiFiNINA/examples/WiFiWebClient
        - ~/Arduino/libraries/WiFiNINA/examples/WiFiWebClientRepeating
        - ~/Arduino/libraries/WiFiNINA/examples/WiFiWebServer
        - examples/StartDriver
      SKETCHES_REPORTS_PATH: sketches-reports
    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: arduino:samd:mkrwifi1010
            platforms: |
              - name: arduino:samd
            artifact-name-suffix: arduino-samd-mkrwifi1010
          - fqbn: arduino:samd:mkrvidor4000
            platforms: |
              - name: arduino:samd
            artifact-name-suffix: arduino-samd-mkrvidor4000
          - fqbn: arduino:samd:nano_33_iot
            platforms: |
              - name: arduino:samd
            artifact-name-suffix: arduino-samd-nano_33_iot
          - fqbn: arduino:megaavr:uno2018:mode=on
            platforms: |
              - name: arduino:megaavr
            artifact-name-suffix: arduino-megaavr-uno2018
          - fqbn: arduino:mbed_nano:nanorp2040connect
            platforms: |
              - name: arduino:mbed_nano
            artifact-name-suffix: arduino-mbed_nano-nanorp2040connect

        include:
          # mkrwifi1010
          - board:
              fqbn: arduino:samd:mkrwifi1010
            sketch-paths: |
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/LedControl
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/PeripheralExplorer
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/Scan
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/ScanCallback
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/SensorTagButton
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/Advertising
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/BatteryMonitor
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/ButtonLED
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/CallbackLED
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/EncryptedBatteryMonitor
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/LED
          # mkrvidor4000
          - board:
              fqbn: arduino:samd:mkrvidor4000
          # nano_33_iot
          - board:
              fqbn: arduino:samd:nano_33_iot
            sketch-paths: |
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/LedControl
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/PeripheralExplorer
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/Scan
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/ScanCallback
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/SensorTagButton
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/Advertising
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/BatteryMonitor
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/ButtonLED
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/CallbackLED
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/EncryptedBatteryMonitor
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/LED
          # uno2018
          - board:
              fqbn: arduino:megaavr:uno2018:mode=on
            sketch-paths: |
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/LedControl
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/PeripheralExplorer
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/Scan
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/ScanCallback
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/SensorTagButton
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/Advertising
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/BatteryMonitor
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/ButtonLED
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/CallbackLED
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/EncryptedBatteryMonitor
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/LED
          # nanorp2040connect
          - board:
              fqbn: arduino:mbed_nano:nanorp2040connect
            sketch-paths: |
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/LedControl
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/PeripheralExplorer
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/Scan
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/ScanCallback
              - ~/Arduino/libraries/ArduinoBLE/examples/Central/SensorTagButton
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/Advertising
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/BatteryMonitor
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/ButtonLED
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/CallbackLED
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/EncryptedBatteryMonitor
              - ~/Arduino/libraries/ArduinoBLE/examples/Peripheral/LED

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Debug
        run: |
          echo $GITHUB_WORKSPACE
          pwd

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            ${{ env.UNIVERSAL_LIBRARIES }}
          sketch-paths: |
            ${{ env.UNIVERSAL_SKETCH_PATHS }}
            ${{ matrix.sketch-paths }}
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save memory usage change report as artifact
        uses: actions/upload-artifact@v6
        with:
          if-no-files-found: error
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: sketches-report-${{ matrix.board.artifact-name-suffix }}
